services:
  netbox:
    ports:
    - 8080:8080
    volumes:
      - netbox-config:/etc/netbox/config:z,ro
      - netbox-media:/opt/netbox/netbox/media:rw
      - netbox-reports:/opt/netbox/netbox/reports:rw
      - netbox-scripts:/opt/netbox/netbox/scripts:rw
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldaps://172.20.2.2"
      AUTH_LDAP_BIND_DN: "CN=netbox,OU=Admin-ServiceAccounts,OU=_Verwaltung,DC=dorsten,DC=local"
      AUTH_LDAP_BIND_PASSWORD: "97aSdox!"
      AUTH_LDAP_USER_SEARCH_BASEDN: "OU=Benutzer,OU=_Verwaltung,DC=dorsten,DC=local"
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=SubGroups,OU=_Verwaltung,DC=dorsten,DC=local"
      AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-Login,OU=_administrativeGruppen,OU=Berechtigungsgruppen,OU=_Verwaltung,DC=dorsten,DC=local"
      AUTH_LDAP_GROUP_TYPE: "NestedGroupOfNamesType"
      AUTH_LDAP_IS_ADMIN_DN: "CN=Netbox-Admin,OU=_administrativeGruppen,OU=Berechtigungsgruppen,OU=_Verwaltung,DC=dorsten,DC=local"
      AUTH_LDAP_IS_SUPERUSER_DN: "CN=Netbox-SU,OU=_administrativeGruppen,OU=Berechtigungsgruppen,OU=_Verwaltung,DC=dorsten,DC=local"
      LDAP_IGNORE_CERT_ERRORS: "true"
      TIME_ZONE: "Europe/Berlin"
      HTTP_PROXIES = { 'http': 'http://wpad.dorsten.local:9090', 'https': 'http://wpad.dorsten.local:9090', }
  redis:
    volumes:
      - netbox-redis-data:/data
  redis-cache:
    volumes:
      - netbox-redis-cache-data:/data
  postgres:
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

volumes:
  netbox-config:
    external: true
  netbox-media:
    external: true
  netbox-reports:
    external: true
  netbox-scripts:
    external: true
  netbox-redis-data:
    external: true
  netbox-redis-cache-data:
    external: true
  netbox-postgres-data:
    external: true
