services:
  netbox:
    ports:
    - 8080:8080
    volumes:
    - ./netbox-docker-config:/etc/netbox/config:z,ro
    - ./netbox-docker-media-files:/opt/netbox/netbox/media:z,rw
    - ./netbox-docker-reports-files:/opt/netbox/netbox/reports:z,rw
    - ./netbox-docker-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-worker:
    volumes:
    - ./netbox-docker-config:/etc/netbox/config:z,ro
    - ./netbox-docker-media-files:/opt/netbox/netbox/media:z,rw
    - ./netbox-docker-reports-files:/opt/netbox/netbox/reports:z,rw
    - ./netbox-docker-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - ./netbox-docker-config:/etc/netbox/config:z,ro
    - ./netbox-docker-media-files:/opt/netbox/netbox/media:z,rw
    - ./netbox-docker-reports-files:/opt/netbox/netbox/reports:z,rw
    - ./netbox-docker-scripts-files:/opt/netbox/netbox/scripts:z,rw

volumes:
  netbox-docker-media-files:
    driver: local
  netbox-docker-config:
    driver: local
  netbox-docker-reports-files:
    driver: local
  netbox-docker-scripts-files:
    driver: local
